#!/bin/bash
# Quick start guide for CyberShield Distributed Setup

echo "=========================================="
echo "CyberShield Distributed Setup Guide"
echo "=========================================="
echo ""

# Get local IP
echo "Step 1: Finding your IP address..."
echo ""
echo "Your local IP addresses:"
ifconfig | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}'
echo ""
echo "Note the IP address of your network interface (usually 192.168.x.x)"
echo ""

# Instructions for Windows central agent
echo "=========================================="
echo "CENTRAL PC (Main Monitoring Station)"
echo "=========================================="
echo ""
echo "1. Ensure agent.py is running:"
echo "   python agent.py"
echo ""
echo "2. Verify it's working:"
echo "   curl http://localhost:5000/api/system"
echo ""
echo "3. Note your PC's IP address (from Step 1)"
echo ""

# Instructions for client PCs
echo "=========================================="
echo "CLIENT PC (Remote Computer to Monitor)"
echo "=========================================="
echo ""
echo "Option A: Using Setup Script (Windows)"
echo "   1. Copy setup_client.bat and agent_client.py to client PC"
echo "   2. Run: setup_client.bat 192.168.1.100"
echo "      (replace 192.168.1.100 with central PC IP)"
echo "   3. Follow the prompts"
echo ""

echo "Option B: Manual Setup (Any OS)"
echo "   1. Copy agent_client.py to client PC"
echo "   2. Install requirements: pip install requests psutil"
echo "   3. Run: python agent_client.py http://192.168.1.100:5000"
echo "      (replace 192.168.1.100 with central PC IP)"
echo ""

# Verification
echo "=========================================="
echo "VERIFICATION"
echo "=========================================="
echo ""
echo "Check if clients connected:"
echo "   curl http://localhost:5000/api/clients"
echo ""
echo "You should see:"
echo "   - clientCount: [number]"
echo "   - clients: [list of connected machines]"
echo ""

echo "=========================================="
echo "Dashboard Update"
echo "=========================================="
echo ""
echo "New tab 'Удаленные ПК' (Remote PCs) will show:"
echo "   ✓ Connected client machines"
echo "   ✓ Real-time CPU/RAM/Disk usage"
echo "   ✓ Security status (Firewall/Antivirus)"
echo "   ✓ Last seen timestamp"
echo "   ✓ Connection status"
echo ""

echo "=========================================="
echo "Troubleshooting"
echo "=========================================="
echo ""
echo "Client can't connect?"
echo "   1. Verify IP is correct: ipconfig /all"
echo "   2. Check firewall allows port 5000"
echo "   3. Test connectivity: ping [central-ip]"
echo ""
echo "Server firewall blocking?"
echo "   Windows: netsh advfirewall firewall add rule name=\"Python 5000\" dir=in action=allow protocol=tcp localport=5000"
echo ""
echo "Client registered but no updates?"
echo "   1. Check client logs for errors"
echo "   2. Verify network connectivity"
echo "   3. Restart client: Ctrl+C then run again"
echo ""

echo "Done! Your distributed monitoring is ready."
